"use client";
import { useState } from "react";
type Row = { id: string; full_name: string | null; first_name: string | null; email: string; user_type: string | null; admin_role: string | null };
export default function AdminTeamManager({ users }: { users: Row[] }) {
 const [roles, setRoles] = useState<Record<string,string>>(() => Object.fromEntries(users.map(u => [u.id, u.user_type === "admin" ? (u.admin_role || "general_admin") : "member"])));
 const [busy,setBusy] = useState<string | null>(null); const [message,setMessage] = useState<Record<string,string>>({});
 async function save(id:string) { setBusy(id); setMessage(m=>({...m,[id]:""})); try { const r=await fetch("/api/admin/team",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId:id,role:roles[id]||"member"})}); const d=await r.json(); setMessage(m=>({...m,[id]:r.ok?"Access updated successfully.":(d.error||"Could not update access.")})); } catch { setMessage(m=>({...m,[id]:"Network error. Please try again."})); } finally {setBusy(null);} }
 return <div className="space-y-4">{users.map(u=>{const current = u.user_type === "admin"; return <article key={u.id} className="rounded-xl border border-carinex-navy/10 p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-semibold text-carinex-navy">{u.full_name||u.first_name||"Unnamed user"}</p><p className="text-sm text-carinex-navy/55">{u.email}</p><p className="mt-1 text-xs text-carinex-navy/45">{current?"Administrator":"Standard member"}</p></div><div className="flex w-full flex-col gap-2 sm:max-w-md"><label className="text-xs font-semibold text-carinex-navy/60">Assign administrator role</label><select value={roles[u.id] || (current ? "general_admin" : "member")} onChange={e=>setRoles(m=>({...m,[u.id]:e.target.value}))} className="w-full rounded-lg border border-carinex-navy/20 bg-white px-3 py-2 text-sm"><option value="member">Standard member — no admin access</option><option value="customer_experience">Customer Experience — users & analytics (view only)</option><option value="financial">Financial — payments & enrollment decisions</option><option value="course_content">Course Content Admin — course content only</option><option value="general_admin">General Admin — full access</option></select><button disabled={busy===u.id} onClick={()=>save(u.id)} className="rounded-full bg-carinex-emerald px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy===u.id?"Saving…":roles[u.id] === "member" ? "Remove admin access" : current?"Update access":"Grant admin access"}</button>{message[u.id]&&<p role="status" className="text-xs text-carinex-navy/70">{message[u.id]}</p>}</div></div></article>})}{users.length===0&&<p className="rounded-xl border border-dashed p-8 text-center text-sm">No users found.</p>}</div>;
}
